# Generated by Django 3.1 on 2020-08-18 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Neighborhood', max_length=100)),
                ('cluster_label', models.IntegerField(blank=True, db_column='Cluster Label', null=True)),
                ('zillow_value', models.IntegerField(blank=True, db_column='Zillow Home Value Index', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mostpopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1st_most_popular_venue', models.CharField(blank=True, db_column='1st Most Common Venue', max_length=100, null=True)),
                ('number_2nd_most_popular_venue', models.CharField(blank=True, db_column='2nd Most Common Venue', max_length=100, null=True)),
                ('number_3rd_most_popular_venue', models.CharField(blank=True, db_column='3rd Most Common Venue', max_length=100, null=True)),
                ('number_4th_most_popular_venue', models.CharField(blank=True, db_column='4th Most Common Venue', max_length=100, null=True)),
                ('number_5th_most_popular_venue', models.CharField(blank=True, db_column='5th Most Common Venue', max_length=100, null=True)),
                ('number_6th_most_popular_venue', models.CharField(blank=True, db_column='6th Most Common Venue', max_length=100, null=True)),
                ('number_7th_most_popular_venue', models.CharField(blank=True, db_column='7th Most Common Venue', max_length=100, null=True)),
                ('number_8th_most_popular_venue', models.CharField(blank=True, db_column='8th Most Common Venue', max_length=100, null=True)),
                ('number_9th_most_popular_venue', models.CharField(blank=True, db_column='9th Most Common Venue', max_length=100, null=True)),
                ('number_10th_most_popular_venue', models.CharField(blank=True, db_column='10th Most Common Venue', max_length=100, null=True)),
                ('neigh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Mostcommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1st_most_common_venue', models.CharField(blank=True, db_column='1st Most Common Venue', max_length=100, null=True)),
                ('number_2nd_most_common_venue', models.CharField(blank=True, db_column='2nd Most Common Venue', max_length=100, null=True)),
                ('number_3rd_most_common_venue', models.CharField(blank=True, db_column='3rd Most Common Venue', max_length=100, null=True)),
                ('number_4th_most_common_venue', models.CharField(blank=True, db_column='4th Most Common Venue', max_length=100, null=True)),
                ('number_5th_most_common_venue', models.CharField(blank=True, db_column='5th Most Common Venue', max_length=100, null=True)),
                ('number_6th_most_common_venue', models.CharField(blank=True, db_column='6th Most Common Venue', max_length=100, null=True)),
                ('number_7th_most_common_venue', models.CharField(blank=True, db_column='7th Most Common Venue', max_length=100, null=True)),
                ('number_8th_most_common_venue', models.CharField(blank=True, db_column='8th Most Common Venue', max_length=100, null=True)),
                ('number_9th_most_common_venue', models.CharField(blank=True, db_column='9th Most Common Venue', max_length=100, null=True)),
                ('number_10th_most_common_venue', models.CharField(blank=True, db_column='10th Most Common Venue', max_length=100, null=True)),
                ('neigh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.neighborhood')),
            ],
        ),
    ]
