# Generated by Django 3.1 on 2020-08-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostcommon',
            name='neigh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comRest', to='blog.neighborhood'),
        ),
        migrations.AlterField(
            model_name='mostpopular',
            name='neigh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popRest', to='blog.neighborhood'),
        ),
    ]
