# Generated by Django 3.1 on 2020-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_both'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='cluster_label',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='cluster_label_com',
            field=models.IntegerField(blank=True, db_column='Cluster Label Common', null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='cluster_label_pop',
            field=models.IntegerField(blank=True, db_column='Cluster Label Popular', null=True),
        ),
    ]
